name: Tag and Release

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      output-sha: ${{ steps.latest-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Calculate next version
        id: calculate_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          dry_run: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version
        env:
          CHANGELOG: ${{ steps.calculate_version.outputs.changelog }}
        run: |
          # Configure git
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          # Update package.json
          npm version "${{ steps.calculate_version.outputs.new_tag }}" --git-tag-version false
          # Update Changelog
          new_changelog="${{ steps.calculate_version.outputs.changelog }}"
          echo -e "# Change Log\n\n${new_changelog}\n$(tail -n +3 CHANGELOG.md)" > CHANGELOG.md
          npx prettier CHANGELOG.md --write
          # Commit and push
          git add package.json CHANGELOG.md
          git commit -m "chore(package): bump version to ${{ steps.calculate_version.outputs.new_tag }}"
          git push

      - name: Output sha of last commit
        id: latest-sha
        run: |
          shaTemp=$(git rev-list HEAD -1)
          echo "sha=${shaTemp}" >> "$GITHUB_OUTPUT"
